HrSystem/Models/GeneralSetting.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GraduationProject.Models
{
    public class GeneralSetting
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Bouns Is Required Field")]
        [Display(Name = "Bouns")]

        public float Extra { get; set; }
        [Required(ErrorMessage = "Deduction Is Required Field")]
        [Display(Name = "Deduction")]

        public float Discount { get; set; }
        [Required(ErrorMessage = "Fitsr Day Is Required Field")]
        [Display(Name = "First Day Off")]

        public string Dayoff_1 { get; set; }
        [Required(ErrorMessage = "Second Day Is Required Field")]
        [Display(Name ="Second Day Off")]

        public string Dayoff_2 { get; set; }
        

    }
}

HrSystem/Controllers/GeneralSettingController.cs
using GraduationProject.Models;
using GraduationProject.Services;
using HrSystem.services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace HrSystem.Controllers
{
    public class GeneralSettingController : Controller
    {
        private GraduationProject.Services.IRepository<GeneralSetting> services;
        public GeneralSettingController(GraduationProject.Services.IRepository<GeneralSetting> _services )
        {
            services = _services;
        }

        public bool flag;
        public IActionResult Index()
        {
         

            List<GeneralSetting> settings = services.GetAll();
            return View(settings);
        }


        public IActionResult Create()
        {
            ViewData["SettingsCount"] = services.GetAll().Count;

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(GeneralSetting gs)
        {
            if (ModelState.IsValid ==true)
            {
                int settingsNumber = services.GetAll().Count;

                    if (settingsNumber==0  )
                    {

                        TempData["Success"] = "Success";
                        services.Insert(gs);
                        return RedirectToAction("Index");

                    }
                
                
                else
                {
                    TempData["error"] = "Can't Created";


                }
            }
            return View("Create",gs);
        }

        public IActionResult Edit(int id)
        {
            GeneralSetting setting = services.GetById(id);
            return View(setting);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id,GeneralSetting gs)
        {
            if (ModelState.IsValid)
            {
                services.Update(id,gs);
                return RedirectToAction("Index");

            }
            return View("Edit",gs);
        }

        public IActionResult Delete(int id)
        {
            services.Delete(id);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            GeneralSetting setting = services.GetById(id);
            return View(setting);
        }

    }
}

HrSystem/Views/GeneralSetting/Create.cshtml
@model GraduationProject.Models.GeneralSetting

<div class="row">
<div class="col-sm-12 col-md-12 col-lg-12">
<h1 class="p-4 my-2">
<img class="mx-3" src="https://img.icons8.com/external-xnimrodx-lineal-color-xnimrodx/64/000000/external-setting-advertising-xnimrodx-lineal-color-xnimrodx-2.png"/>New Setting</h1>
<hr />
</div>
</div>
@if ( TempData["error"] != null )
{
<div class="alert alert-danger text-center w-25 mx-auto" style="color:white;">@TempData["error"]</div>
}
@if (ViewBag.SettingsCount != 0)
{
    <div class="text-danger my-2 text-center">General Setting already created</div>
}

<div class="row">
<div class="col-md-12 col-sm-12 col-lg-12">
<form asp-controller="GeneralSetting" asp-action="Create">
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group">
<label asp-for="Extra" class="col-md-3 control-label"></label>
<div class="col-md-9 mx-3">
<input asp-for="Extra" class="form-control" />
</div>
<span asp-validation-for="Extra" class="text-danger"></span>
</div>
<div class="form-group">
<label asp-for="Discount" class="col-md-3 control-label"></label>
<div class="col-md-9 mx-3">
<input asp-for="Discount" class="form-control" />
</div>
<span asp-validation-for="Discount" class="text-danger"></span>
</div>
<div class="form-group">
<label asp-for="Dayoff_1" class="col-md-3 control-label"></label>
<div class="col-md-9 mx-3">
<select class="form-control" asp-for="Dayoff_1" id="select1" onchange="Value(this.value)">
<option value="" disabled selected>Select your option</option>
<option value="Friday">Friday</option>
<option value="Saturday">Saturday</option>
<option value="Sunday">Sunday</option>
<option value="Monday">Monday</option>
<option value="Tuesday">Tuesday</option>
<option value="Wednesday">Wednesday</option>
<option value="Thursday">Thursday</option>
</select>
</div>
<span asp-validation-for="Dayoff_1" class="text-danger"></span>
</div>
<div class="form-group">
<label asp-for="Dayoff_2" class="col-md-3 control-label"></label>
<div class="col-md-9 mx-3">
<select class="form-control" asp-for="Dayoff_2" id="select2" onchange="Value2(this.value)">
<option value="" disabled selected>Select your option</option>
<option value="Friday">Friday</option>
<option value="Saturday">Saturday</option>
<option value="Sunday">Sunday</option>
<option value="Monday">Monday</option>
<option value="Tuesday">Tuesday</option>
<option value="Wednesday">Wednesday</option>
<option value="Thursday">Thursday</option>
</select>
</div>
<span asp-validation-for="Dayoff_2" class="text-danger"></span>
</div>
@if (ViewBag.SettingsCount == 0)
{
<div class="d-flex justify-content-center">

 <span class="form-group mx-3">
<input type="submit" value="ADD" class="btn btn-primary" />
</span>
<span class="form-group">
<a asp-controller="GeneralSetting" asp-action="Index" class="btn btn-danger">Cancel</a>
</span>
</div>

 }
else
{
<div class="d-flex justify-content-center">

 <span class="form-group mx-3">
<input type="submit" disabled value="ADD" class="btn btn-primary" />
</span>
<span class="form-group">
<a asp-controller="GeneralSetting" asp-action="Index" class="btn btn-danger">Cancel</a>
</span>
</div>

}

</form>
</div>
</div>


@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    function Value(select1) {
        if (select1 != "") {
            $("#select2 option[value='" + select1 + "']").hide();
        }
    }

        function Value2(select2) {
        if (select2 != "") {
            $("#select1 option[value='" + select2 + "']").hide();
        }
    }
</script>
  

HrSystem/Views/GeneralSetting/Details.cshtml
@model GraduationProject.Models.GeneralSetting

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>GeneralSetting</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Extra)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Extra)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dayoff_1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dayoff_1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dayoff_2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dayoff_2)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

HrSystem/Views/GeneralSetting/Edit.cshtml
@model GraduationProject.Models.GeneralSetting

<div class="row">
<div class="col-sm-12 col-md-12 col-lg-12">
<h1 class="p-4 my-2">
<img class="mx-3" src="https://img.icons8.com/external-xnimrodx-lineal-color-xnimrodx/64/000000/external-setting-advertising-xnimrodx-lineal-color-xnimrodx-2.png"/>Edit Setting</h1>
<hr />
</div>
</div>

<div class="row">
<div class="col-md-12 col-sm-12 col-lg-12">
<form asp-controller="GeneralSetting" asp-action="Edit" asp-route-id="@Model.ID">
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group">
<label asp-for="Extra" class="col-md-3 control-label"></label>
<div class="col-md-9 mx-3">
<input asp-for="Extra" class="form-control" />
</div>
<span asp-validation-for="Extra" class="text-danger"></span>
</div>
<div class="form-group">
<label asp-for="Discount" class="col-md-3 control-label"></label>
<div class="col-md-9 mx-3">
<input asp-for="Discount" class="form-control" />
</div>
<span asp-validation-for="Discount" class="text-danger"></span>
</div>
<div class="form-group">
<label asp-for="Dayoff_1" class="col-md-3 control-label"></label>
<div class="col-md-9 mx-3">
<select class="form-control" asp-for="Dayoff_1" id="select1" onchange="Value(this.value)">
<option value="" disabled selected>Select your option</option>
<option value="Friday">Friday</option>
<option value="Saturday">Saturday</option>
<option value="Sunday">Sunday</option>
<option value="Monday">Monday</option>
<option value="Tuesday">Tuesday</option>
<option value="Wednesday">Wednesday</option>
<option value="Thursday">Thursday</option>
</select>
</div>
<span asp-validation-for="Dayoff_1" class="text-danger"></span>
</div>
<div class="form-group">
<label asp-for="Dayoff_2" class="col-md-3 control-label"></label>
<div class="col-md-9 mx-3">
<select class="form-control" asp-for="Dayoff_2" id="select2" onchange="Value2(this.value)">
<option value="" disabled selected>Select your option</option>
<option value="Friday">Friday</option>
<option value="Saturday">Saturday</option>
<option value="Sunday">Sunday</option>
<option value="Monday">Monday</option>
<option value="Tuesday">Tuesday</option>
<option value="Wednesday">Wednesday</option>
<option value="Thursday">Thursday</option>
</select>
</div>
<span asp-validation-for="Dayoff_2" class="text-danger"></span>
</div>
<div class="d-flex justify-content-center">
<span class="form-group mx-3">
<input type="submit" value="Save" class="btn btn-primary" />
</span>
<span class="form-group">
<a asp-controller="GeneralSetting" asp-action="Index" class="btn btn-danger">Cancel</a>
</span>
</div>
</form>
</div>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    function Value(select1) {
        if (select1 != "") {
            $("#select2 option[value='" + select1 + "']").hide();
        }
    }

    function Value2(select2) {
        if (select2 != "") {
            $("#select1 option[value='" + select2 + "']").hide();
        }
    }
</script>

HrSystem/Views/GeneralSetting/Index.cshtml
@model IEnumerable<GraduationProject.Models.GeneralSetting>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h1 class="p-4 my-2">
            <img class="mx-3" src="https://img.icons8.com/external-xnimrodx-lineal-color-xnimrodx/64/000000/external-setting-advertising-xnimrodx-lineal-color-xnimrodx-2.png" />General Settings
        </h1>
    </div>
</div>
<div class="row">
<div class="col-sm-12 col-md-12 col-lg-12 " >
<a class="btn btn-danger" style="float:right;clear:both;" asp-controller="GeneralSetting" asp-action="Create">Add New General Settings</a>
<div style="clear:both;"></div>
<hr />
</div>
</div>
@if ( TempData["Success"] != null )
{
<div class="alert alert-success text-center w-25 mx-auto" style="color:white;">@TempData["success"]</div>
}

<div class="row">
<div class="col-sm-12 col-md-12 col-lg-12">
<table class="table table-striped table-bordered zero-configuration">
<thead>
<tr>
<th>
@Html.DisplayNameFor(model => model.Extra)
</th>
<th>
@Html.DisplayNameFor(model => model.Discount)
</th>
<th>
@Html.DisplayNameFor(model => model.Dayoff_1)
</th>
<th>
@Html.DisplayNameFor(model => model.Dayoff_2)
</th>
<th></th>
</tr>
</thead>
<tbody>
@foreach (var item in Model) {
<tr>
<td>
@Html.DisplayFor(modelItem => item.Extra)
</td>
<td>
@Html.DisplayFor(modelItem => item.Discount)
</td>
<td>
@Html.DisplayFor(modelItem => item.Dayoff_1)
</td>
<td>
@Html.DisplayFor(modelItem => item.Dayoff_2)
</td>
<td>
<a class="btn btn-info" asp-controller="GeneralSetting" asp-action="Edit" asp-route-id="@item.ID" onclick="Edit()">Edit</a>
<a class="btn btn-danger" asp-controller="GeneralSetting" asp-action="Delete" asp-route-id="@item.ID" onclick="Delete()">Delete</a>
</td>
</tr>
}
</tbody>
</table>
</div>
</div>
<script>
function Edit(){
var respond=confirm("Do You Want To Edit?!");
if(!respond){
event.preventDefault();
}
}

 function Delete(){
var respond=confirm("Do You Want To Delete?!");
if(!respond){
event.preventDefault();
}
}
</script>