HrSystem/Controllers/AttendanceController.cs
using GraduationProject.Models;
using GraduationProject.Services;
using GraduationProject.ViewModels;
using HrSystem.services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace GraduationProject.Controllers
{
    [Authorize]
    public class AttendanceController : Controller
    {
        private readonly IRepository<Attendance_Leaving> repAttend;
        private readonly IRepository<Employee> repEmp;
        private readonly HRSystem hRSystem;

        public AttendanceController(IRepository<Employee> RepEmp,IRepository<Attendance_Leaving> RepAttend, HRSystem hRSystem)
        {
            repAttend = RepAttend;
            this.hRSystem = hRSystem;
            repEmp = RepEmp;

        }
        public IActionResult Index()
        {
            var AllAttendance = repAttend.GetAll();
            return View(AllAttendance);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Show(SearchAttendanceViewModel MyView)
        {
            if (ModelState.IsValid == true)
            {
                var ValidEmpName = hRSystem.Attendance_Leavings.Where(e => e.Emp.Name.Contains(MyView.Search)).Count();
                var ValidDeptName = hRSystem.Attendance_Leavings.Where(e => e.Emp.Dept.Name.Contains(MyView.Search)).Count();
                var record = hRSystem.Attendance_Leavings.Where(e => e.Date >= MyView.From && e.Date <= MyView.To && (e.Emp.Dept.Name.Contains(MyView.Search) || e.Emp.Name.Contains(MyView.Search))).Include(e => e.Emp).Include(e => e.Emp.Dept).Count();
                if (ValidEmpName==0 && ValidDeptName==0)
                {
                    ModelState.AddModelError("Search", "Employee Name or Department Not Found");

                }
                else if( MyView.From > MyView.To)
                {
                    ModelState.AddModelError("From", "enter Valid Date From");

                }
                else if (record == 0)
                {
                    ModelState.AddModelError("Search", "There is No Recorded Available");

                }
                else
                {
                    var Attend = hRSystem.Attendance_Leavings.Where(e => e.Date >= MyView.From && e.Date <= MyView.To && (e.Emp.Dept.Name.Contains(MyView.Search) || e.Emp.Name.Contains(MyView.Search))).Include(e => e.Emp).Include(e => e.Emp.Dept).ToList();
                    return View(Attend);
                }


            }
            return View("AttendanceBySearch",MyView);
        }

        public IActionResult AttendanceBySearch()
        {
            return View();
        }


        public IActionResult Delete(int id)
        {

            repAttend.Delete(id);
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)

        {
            
            ViewData["Emp"] = repEmp.GetAll();

            var Attend = repAttend.GetById(id);

            return View(Attend);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveEdit(int id, Attendance_Leaving EditAttend)
        {
            var empAttendTime = TimeSpan.Parse(hRSystem.Employees.Where(e => e.ID == EditAttend.Emp_ID).Select(e => e.AttendanceTime).First());
            int ArriveHour = empAttendTime.Hours;
            var empLeaveTime = TimeSpan.Parse(hRSystem.Employees.Where(e => e.ID == EditAttend.Emp_ID).Select(e => e.LeavingTime).First());
            var LeaveHour = empLeaveTime.Hours;
          
var previousAttend = hRSystem.Attendance_Leavings.Where(a => a.Date == EditAttend.Date && a.Emp_ID == EditAttend.Emp_ID).Count();


            var newattend = TimeSpan.Parse(EditAttend.AttendanceTime);
            int AttendHour = newattend.Hours;
            if (ModelState.IsValid == true)
            {
                if (AttendHour < ArriveHour)
                {

                    ModelState.AddModelError("AttendanceTime", $"AttendanceTime can't be less than {ArriveHour}");

                }
                else if (TimeSpan.Parse(EditAttend.AttendanceTime).Hours >= TimeSpan.Parse(EditAttend.LeavingTime).Hours)
                {
                    ModelState.AddModelError("AttendanceTime", "AttendanceTime Cant be greater than Leaving Time or Equal");

                }
                else if (TimeSpan.Parse(EditAttend.LeavingTime).Hours < LeaveHour)
                {
                    ModelState.AddModelError("LeavingTime", $"LeavingTime can't be less than {LeaveHour}");

                }
                else if (previousAttend != 0)
                {
                    ModelState.AddModelError("Date", $"This Date already recorded ");

                }
                else
                {
                    repAttend.Update(id, EditAttend);
                    return RedirectToAction("Index");
                }
            }
            ViewData["Emp"] = repEmp.GetAll();


            return View("Edit", EditAttend);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(Attendance_Leaving Newobj)
        {
            var empAttendTime = TimeSpan.Parse(hRSystem.Employees.Where(e=>e.ID==Newobj.Emp_ID).Select(e => e.AttendanceTime).First());
            int ArriveHour = empAttendTime.Hours;
            var empLeaveTime = TimeSpan.Parse(hRSystem.Employees.Where(e => e.ID == Newobj.Emp_ID).Select(e => e.LeavingTime).First());
            var LeaveHour = empLeaveTime.Hours;

            var newattend = TimeSpan.Parse(Newobj.AttendanceTime);
            int AttendHour = newattend.Hours;
          
var previousAttend = hRSystem.Attendance_Leavings.Where(a => a.Date == Newobj.Date && a.Emp_ID == Newobj.Emp_ID).Count();


            if (ModelState.IsValid == true)
            {
                if(AttendHour < ArriveHour)
                {
                    
                    ModelState.AddModelError("AttendanceTime", $"AttendanceTime can't be less than {ArriveHour}");

                }
                else if (TimeSpan.Parse(Newobj.AttendanceTime).Hours >= TimeSpan.Parse(Newobj.LeavingTime).Hours)
                {
                    ModelState.AddModelError("AttendanceTime", "AttendanceTime Cant be greater than Leaving Time or Equal");

                }
                else if(TimeSpan.Parse(Newobj.LeavingTime).Hours< LeaveHour)
                {
                    ModelState.AddModelError("LeavingTime", $"LeavingTime can't be less than {LeaveHour}");

                }
                else if (previousAttend != 0)
                {
                    ModelState.AddModelError("Date", $"This Date already recorded ");

                }
                else
                {
                    repAttend.Insert(Newobj);
                    return RedirectToAction("Index");
                }


            }
            ViewData["Emp"] = repEmp.GetAll();

            return View("New", Newobj);
        }

        public IActionResult New()
        {
            ViewData["Emp"] = repEmp.GetAll();
            return View();
        }
    }
}

HrSystem/Views/Attendance/AttendanceBySearch.cshtml
@model GraduationProject.ViewModels.SearchAttendanceViewModel

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h1 class="p-4 my-2">
            <img class="mx-3" src="https://img.icons8.com/ios/50/000000/attendance-mark.png"/>Attendance</h1>
        <hr />
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-lg-12">
        <form asp-controller="Attendance" asp-action="Show">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Search" class="col-md-3 control-label"></label>
                <div class="col-md-9 mx-3">
                <input type="search" asp-for="Search" class="form-control" />
                </div>
                <span asp-validation-for="Search" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="From" class="col-md-3 control-label"></label>
                <div class="col-md-9 mx-3">
                <input asp-for="From" class="form-control" />
                </div>
                <span asp-validation-for="From" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="To" class="col-md-3 control-label"></label>
                <div class="col-md-9 mx-3">
                <input asp-for="To" class="form-control" />
                </div>
                <span asp-validation-for="To" class="text-danger"></span>
            </div>
            <div class="form-group d-flex justify-content-center">
                <span class="mx-3">
                    <input type="submit" value="Search" class="btn btn-primary" />

                </span>
                <span >
                    <a class="btn btn-info" asp-controller="Attendance" asp-action="New">Add Attendance</a>
                </span>
                <span class="mx-3">
                    <a class="btn btn-danger" asp-controller="Attendance" asp-action="Index">Cancel</a>
                </span>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HrSystem/Views/Attendance/Edit.cshtml
@model GraduationProject.Models.Attendance_Leaving
@{
    SelectList Emp = new SelectList(ViewBag.Emp, "ID", "Name");
}
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h1 class="p-4 my-2"> <img class="mx-3" src="https://img.icons8.com/external-flaticons-lineal-flat-icons/64/000000/external-form-customer-feedback-flaticons-lineal-flat-icons.png"/>Edit Attendance</h1>
        <hr />
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-lg-12">
        <form asp-controller="Attendance" asp-action="SaveEdit" asp-route-id="@Model.ID">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date" class="col-md-3 control-label"></label>
                <div class="col-md-9 mx-3">
                <input asp-for="Date" class="form-control" />
                </div>
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AttendanceTime" class="col-md-3 control-label"></label>
                <div class="col-md-9 mx-3">
                <input asp-for="AttendanceTime" class="form-control" />
                </div>
                <span asp-validation-for="AttendanceTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeavingTime" class="col-md-3 control-label"></label>
                <div class="col-md-9 mx-3">
                <input asp-for="LeavingTime" class="form-control" />
                </div>
                <span asp-validation-for="LeavingTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Emp_ID" class="col-md-3 control-label"></label>
                <div class="col-md-9 mx-3">
                <select asp-for="Emp_ID" class ="form-control" asp-items="Emp"></select>
                </div>
            </div>
            <div class="d-flex justify-content-center">
                <span class="form-group mx-2">
                <input type="submit" value="Save" class="btn btn-primary" />
            </span>
            <span class="form-group">
                <a asp-controller="Attendance" asp-action="Index" class="btn btn-danger">Cancel</a>
            </span>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HrSystem/Views/Attendance/Index.cshtml
@model IEnumerable<GraduationProject.Models.Attendance_Leaving>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h1 class="p-4 my-2">
            <img class="mx-3" src="https://img.icons8.com/ios/50/000000/attendance-mark.png"/>Attendance</h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
<div class="text-center mb-3">
    <span class="mx-2">
        <a asp-controller="Attendance" asp-action="AttendanceBySearch">
        <img style="width:50px;height50px;" src="/Images/icons8-search.gif" />
        </a>
    </span>
    <span class="mx-2">
        <a  asp-controller="Attendance" asp-action="New">
            <img src="https://img.icons8.com/ios/50/000000/add--v1.png"/></a>
    </span>
</div>
</div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        
<table class="table table-striped table-bordered zero-configuration">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AttendanceTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeavingTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Emp)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AttendanceTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LeavingTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Emp.Name)
            </td>
            <td>
                <a class="btn btn-info" asp-controller="Attendance" asp-action="Edit" asp-route-id="@item.ID" onclick="Edit()">Edit</a>
                <a class="btn btn-danger" asp-controller="Attendance" asp-action="Delete" asp-route-id="@item.ID" onclick="Delete()">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>
</div>
<script>
    function Edit(){
        var respond=confirm("Do You Want To Edit?!");
        if(!respond){
            event.preventDefault();
        }
    }

    function Delete(){
        var respond=confirm("Do You Want To Delete?!");
        if(!respond){
            event.preventDefault();
        }
    }
</script>

HrSystem/Views/Attendance/New.cshtml
@model GraduationProject.Models.Attendance_Leaving
@{
    SelectList Emp = new SelectList(ViewBag.Emp, "ID", "Name");
}
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h1 class="p-4 my-2"> <img class="mx-3" src="https://img.icons8.com/external-flaticons-lineal-flat-icons/64/000000/external-form-customer-feedback-flaticons-lineal-flat-icons.png"/>Attendance Form</h1>
        <hr />
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-lg-12">
        <form asp-controller="Attendance" asp-action="Insert">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date" class="col-md-3 control-label"></label>
                <div class="col-md-9 mx-3">
                <input asp-for="Date" class="form-control" />
                </div>
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AttendanceTime" class="col-md-3 control-label"></label>
                <div class="col-md-9 mx-3">
                <input asp-for="AttendanceTime" class="form-control" />
                </div>
                <span asp-validation-for="AttendanceTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeavingTime" class="col-md-3 control-label"></label>
                <div class="col-md-9 mx-3">
                <input asp-for="LeavingTime" class="form-control" />
                </div>
                <span asp-validation-for="LeavingTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Emp_ID" class="col-md-3 control-label"></label>
                <div class="col-md-9 mx-3">
                <select asp-for="Emp_ID" class ="form-control" asp-items="Emp"></select>
                </div>
            </div>
            <div class="d-flex justify-content-center">
                <span class="form-group mx-2">
                <input type="submit" value="ADD" class="btn btn-primary" />
            </span>
            <span class="form-group">
                <a asp-controller="Attendance" asp-action="Index" class="btn btn-danger">Cancel</a>
            </span>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HrSystem/Views/Attendance/Show.cshtml
@model List<GraduationProject.Models.Attendance_Leaving>
<style>
    .print:hover{
        cursor:pointer;
    }
</style>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h1 class="p-4 my-2">
            <img class="mx-3" src="https://img.icons8.com/ios/50/000000/attendance-mark.png"/>Attendance</h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
<div class="text-center my-2">
    <span class="mx-2">
        <a asp-controller="Attendance" asp-action="AttendanceBySearch">
        <img style="width:50px;height50px;" src="/Images/icons8-search.gif" />
        </a>
    </span>
    <span class="mx-2">
        <a  asp-controller="Attendance" asp-action="New">
            <img src="https://img.icons8.com/ios/50/000000/add--v1.png"/></a>
    </span>
    <span class="mx-2">
        <img class="print" src="https://img.icons8.com/ios-glyphs/30/000000/print.png" onclick="print()"/>

    </span>
</div>
</div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        
<table class="table table-striped table-bordered zero-configuration">
    <thead  >
        <tr>
           
            <th>
                 Department
            </th>
            <th>
                EmployeeName
            </th>
            <th>
                Date
            </th>
            <th>
                AttendanceTime
            </th>
            <th>
                LeavingTime
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

@foreach (var item in Model) {
        <tr id="frame">
            
            <td>
                @item.Emp.Dept.Name
            </td>
            <td>
                @item.Emp.Name
            </td>
            <td>
                @item.Date
            </td>
            <td>
                @item.AttendanceTime
            </td>
            <td>
                @item.LeavingTime
            </td>
            <td>
                <a class="btn btn-info" asp-controller="Attendance" asp-action="Edit" asp-route-id="@item.ID" onclick="Edit()">Edit</a>
                <a class="btn btn-danger" asp-controller="Attendance" asp-action="Delete" asp-route-id="@item.ID" onclick="Delete()">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>
</div>
<script>
    function Edit(){
        var respond=confirm("Do You Want To Edit?!");
        if(!respond){
            event.preventDefault();
        }
    }

    function Delete(){
        var respond=confirm("Do You Want To Delete?!");
        if(!respond){
            event.preventDefault();
        }
    }
</script>
@*<script>
function print() {
var divContents = document.getElementById("frame").innerHTML;
//var prnt = window.open('', '', 'height=500, width=800');
//prnt .document.write(`<html><head><title>Print Page</title>`);
//prnt .document.write(`</head><body>`);
//prnt .document.write(divContents.innerHTML);
//prnt .document.write(`</body></html>`);
prnt .print();
}
</script>*@