HrSystem/ViewModels/SalaryReport.cs
using System.ComponentModel.DataAnnotations;

namespace HrSystem.ViewModel
{


    public class SalaryReport
    {
        [Required]
        public string Search { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }

        public int AttendanceDayNumbers { get; set; }
        public int AbsenceDayNumbers { get; set; }

        public float ExtraHours { get; set; }
        public float DeductionHours { get; set; }

        public float TotalBonus { get; set; }
        public float TotalDeduction { get; set; }

        public float NetSalary { get; set; }

    }
}

HrSystem/Controllers/SalaryReportController.cs
using GraduationProject.Models;
using GraduationProject.Services;
using HrSystem.services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using HrSystem.ViewModel;
using System.Globalization;

namespace HrSystem.Controllers
{
    public class SalaryReportController : Controller
    {
        private IRepository<Employee> employee;
        private GraduationProject.Services.IRepository<Attendance_Leaving> attendance;
        private GraduationProject.Services.IRepository<GeneralSetting> setting;
        private HRSystem db;
        GraduationProject.Services.IRepository<OfficialHolidays> holidays;
        public SalaryReportController( IRepository<Employee> _employee,
                                      GraduationProject.Services.IRepository<OfficialHolidays> _holidays,
                                      GraduationProject.Services.IRepository<Attendance_Leaving> _attendance,
                                      GraduationProject.Services.IRepository<GeneralSetting> _setting,
                                      HRSystem _dp)
        {
            employee = _employee;
            holidays = _holidays;
            attendance = _attendance;
            setting = _setting;
            db = _dp;
        }
     
       public int CountHolidays(int month, int year)
        {
          return( holidays.GetAll().Where(x=>x.Date.Month==month&& x.Date.Year==year).Count()+8);

        }
       public int AttendanceDays(string name,int month,int year)
        {
            var countDays = db.Attendance_Leavings.Where(x => x.Emp.Name == name && x.Date.Month == month && x.Date.Year == year).Count();
            return countDays;
        }
       public int AbsenceDays(string name,int month,int year)
        {
            var x=30-((AttendanceDays(name,month,year)+CountHolidays(month,year)));
            return x;
        }
       public float DeductionHours(string name,int month, int year)
        {
            float totalDeductionHours=0;
            float deductionHours = 0;
            var emplyeeInfo= db.Employees.FirstOrDefault(x=>x.Name==name);
            var setting = db.General_Settings.FirstOrDefault();
            var daysInfo = db.Attendance_Leavings.Where(x => x.Emp.Name == name && x.Date.Month == month && x.Date.Year == year).ToList();
            foreach (var day in daysInfo)
            {
                if (TimeSpan.Parse(day.AttendanceTime).Hours > TimeSpan.Parse(emplyeeInfo.AttendanceTime).Hours)
                {
                    deductionHours +=TimeSpan.Parse(day.AttendanceTime).Hours-TimeSpan.Parse(emplyeeInfo.AttendanceTime).Hours;
                    totalDeductionHours =deductionHours * setting.Discount;
                }
            }
            return totalDeductionHours;
        }
       public float BounsHours(string name, int month, int year)
        {
            float totalBounsHours = 0;
            float BounsHours = 0;
            var emplyeeInfo = db.Employees.FirstOrDefault(x => x.Name == name);
            var setting = db.General_Settings.FirstOrDefault();
            var daysInfo = db.Attendance_Leavings.Where(x => x.Emp.Name == name && x.Date.Month == month && x.Date.Year == year).ToList();
            foreach (var day in daysInfo)
            {
                if (TimeSpan.Parse(day.LeavingTime).Hours > TimeSpan.Parse(emplyeeInfo.LeavingTime).Hours)
                {
                    BounsHours += TimeSpan.Parse(day.LeavingTime).Hours - TimeSpan.Parse(emplyeeInfo.LeavingTime).Hours;
                    totalBounsHours = BounsHours * setting.Extra;
                }
            }
            return totalBounsHours;
        }
       public float NetBouns(string name, int month, int year)
        {
            var employee = db.Employees.FirstOrDefault(x => x.Name == name);
            var daysInfo = db.Attendance_Leavings.Where(x => x.Emp.Name == name && x.Date.Month == month && x.Date.Year == year).ToList();
            var salaryPerHour = employee.Salary/( 30*(TimeSpan.Parse(employee.LeavingTime).Hours-TimeSpan.Parse(employee.AttendanceTime).Hours));
            var netBouns=salaryPerHour*BounsHours(name, month, year);

            return netBouns;
        }
       public float NetDeduction(string name, int month, int year)
        {
            var employee = db.Employees.FirstOrDefault(x => x.Name == name);
            var daysInfo = db.Attendance_Leavings.Where(x => x.Emp.Name == name && x.Date.Month == month && x.Date.Year == year).ToList();
            var salaryPerHour = employee.Salary / (30 * (TimeSpan.Parse(employee.LeavingTime).Hours - TimeSpan.Parse(employee.AttendanceTime).Hours));
            var netBouns = salaryPerHour * DeductionHours(name, month, year);

            return netBouns;
        }
       public float NetSalary(string name, int month, int year)
        {
            var employee = db.Employees.FirstOrDefault(x => x.Name == name);
            var Salary = (30-AbsenceDays(name,month,year))* (TimeSpan.Parse(employee.LeavingTime).Hours - TimeSpan.Parse(employee.AttendanceTime).Hours)* employee.Salary / (30 * (TimeSpan.Parse(employee.LeavingTime).Hours - TimeSpan.Parse(employee.AttendanceTime).Hours));
            var netSalary=(Salary-NetDeduction(name,month,year))+NetBouns(name,month,year);
            return netSalary;
        }
    

        public IActionResult GetReport()
        {
            return View();
        }
        public IActionResult CreateReport(SalaryReport report)
        {

            if (ModelState.IsValid == true)
            {
                var Check = db.Employees.Where(e => e.Name.Equals(report.Search)).Include(e => e.Dept).ToList().Count();
                var record = db.Attendance_Leavings.Where(n => n.Emp.Name == report.Search && n.Date.Month == report.Month && n.Date.Year == report.Year).Count();
                var validateGeneralSettings = db.General_Settings.Count();
                if (Check == 0)
                {
                    ModelState.AddModelError("Search", "Employee Name InValid");
                }
                else if (report.Year < 2008 || report.Year >DateTime.Now.Year)
                {
                    ModelState.AddModelError("Year", "Enter Valid Year");
                }
                else if (report.Month > DateTime.Now.Month && report.Year==DateTime.Now.Year)
                {
                    DateTime date = new DateTime(DateTime.Now.Year,report.Month,DateTime.Now.Day);

                    ModelState.AddModelError("Month", $"{date.ToString("MMMM")} greater than current Month");

                }
                else if(record == 0)
                {
                    ModelState.AddModelError("Search"," No available records here!");
                }
                else if(validateGeneralSettings==0)
                {
                    ModelState.AddModelError("Search", "Kindly add the general settings fisrt");
                }

                else
                {
                    ViewData["emp"] = db.Employees.Where(e => e.Name.Equals(report.Search)).Include(e => e.Dept).ToList();
                    report.AttendanceDayNumbers = AttendanceDays(report.Search, report.Month, report.Year);
                    report.AbsenceDayNumbers = AbsenceDays(report.Search, report.Month, report.Year);
                    report.ExtraHours = BounsHours(report.Search, report.Month, report.Year);
                    report.DeductionHours = DeductionHours(report.Search, report.Month, report.Year);
                    report.TotalBonus = NetBouns(report.Search, report.Month, report.Year);
                    report.TotalDeduction = NetDeduction(report.Search, report.Month, report.Year);
                    report.NetSalary = NetSalary(report.Search, report.Month, report.Year);
                    return View(report);
                }
            }
            return View("GetReport",report);
        }
        public ActionResult Index()
        {
            return View();
        }
        public IActionResult Details(SalaryReport report)
        {
            ViewData["Emp"] = db.Employees.Where(e => e.Name.Equals(report.Search)).Include(e => e.Dept).FirstOrDefault();
            var Attend = db.Attendance_Leavings.Where(e => e.Date.Month == report.Month && e.Date.Year == report.Year && e.Emp.Name.Equals(report.Search)).ToList();
            ViewData["General"] = db.General_Settings.FirstOrDefault();
            ViewData["Holidays"] = db.OfficialHolidays.Where(e => e.Date.Month == report.Month && e.Date.Year == report.Year).ToList();
            ViewData["Rep"] = report;
            return View(Attend);
        }
      
    }
}

HrSystem/Views/SalaryReport/CreateReport.cshtml
@model HrSystem.ViewModel.SalaryReport
    <style>
        .print:hover {
            cursor: pointer;
        }
        .table-wrapper{
            max-width:100%;
            overflow-x:scroll;
        }
    </style>
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <h1 class="p-4 my-2">
                <img class="mx-3" src="https://img.icons8.com/ios-glyphs/30/000000/salary-female.png" />Salary Report
            </h1>
            <hr />
        </div>
    </div>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">

        <form asp-action="CreateReport">


            <div class="col-md-9 mx-3 form-group">
                <input type="text" class="form-control" placeholder="Kindly enter employee name" asp-for="Search" />
                <span asp-validation-for="Search" class="text-danger"></span>
            </div>

            <div class="form-group">
                @*<label class="col-md-3 label-control">Month</label>*@
                <div class="col-md-9 mx-3">
                    <select class="form-control" id="month" asp-for="Month">
                        <option selected disabled>Month</option>
                        <option value="01">January</option>
                        <option value="02">February</option>
                        <option value="03">March</option>
                        <option value="04">April</option>
                        <option value="05">May</option>
                        <option value="06">June</option>
                        <option value="07">July</option>
                        <option value="08">August</option>
                        <option value="09">September</option>
                        <option value="10">October</option>
                        <option value="11">November</option>
                        <option value="12">December</option>
                    </select>
                </div>
                <span asp-validation-for="Month" class="text-danger"></span>
            </div>

            <div class="form-group">
                @*<label class="col-md-3 label-control">Year</label>*@
                <div class="col-md-9 mx-3">
                    <select class="form-control" id="year" asp-for="Year">
                        <option selected disabled>Year</option>
                        <option value="1990">1990</option>
                        <option value="1991">1991</option>
                        <option value="1992">1992</option>
                        <option value="1993">1993</option>
                        <option value="1994">1994</option>
                        <option value="1995">1995</option>
                        <option value="1996">1996</option>
                        <option value="1997">1997</option>
                        <option value="1998">1998</option>
                        <option value="1999">1999</option>
                        <option value="2000">2000</option>
                        <option value="2001">2001</option>
                        <option value="2002">2002</option>
                        <option value="2003">2003</option>
                        <option value="2004">2004</option>
                        <option value="2005">2005</option>
                        <option value="2006">2006</option>
                        <option value="2007">2007</option>
                        <option value="2008">2008</option>
                        <option value="2009">2009</option>
                        <option value="2010">2010</option>
                        <option value="2011">2011</option>
                        <option value="2012">2012</option>
                        <option value="2013">2013</option>
                        <option value="2014">2014</option>
                        <option value="2015">2015</option>
                        <option value="2016">2016</option>
                        <option value="2017">2017</option>
                        <option value="2018">2018</option>
                        <option value="2019">2019</option>
                        <option value="2020">2020</option>
                        <option value="2021">2021</option>
                        <option value="2022">2022</option>
                        <option value="2023">2023</option>
                        <option value="2024">2024</option>
                        <option value="2025">2025</option>
                        <option value="2026">2026</option>
                        <option value="2027">2027</option>
                        <option value="2028">2028</option>
                    </select>
                </div>
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>


            <div class="form-group d-flex justify-content-center">
                <input type="submit" value="Search" class="btn btn-info" />
            </div>

        </form>

    </div>
</div>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <div class="table-wrapper">
        <table class="text-center table table-striped table-bordered zero-configuration">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Department
                    </th>
                    <th>
                        Salary
                    </th>
                    <th>
                        Attendance
                    </th>
                    <th>
                        Absence
                    </th>
                    <th>
                        Overtime hours
                    </th>
                    <th>
                        Deducted hours
                    </th>
                    <th>
                        Bonus
                    </th>
                    <th>
                        Deduction
                    </th>
                    <th>
                        Total
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.emp)
                    {
                <tr>
                    <td class="my-auto">
                            @item.Name
                        </td>
                        <td>
                            @item.Dept.Name
                        </td>

                        <td>
                            @item.Salary

                        </td>

                    <td>
                        @Model.AttendanceDayNumbers
                    </td>
                    <td>
                        @Model.AbsenceDayNumbers

                    </td>
                    <td>
                        @Model.ExtraHours

                    </td>
                    <td>
                        @Model.DeductionHours

                    </td>
                    <td>
                        @Model.TotalBonus EGP
                    </td>
                    <td>
                        @Model.TotalDeduction EGP
                    </td>
                    <td>
                        @Model.NetSalary EGP
                    </td>
                    <td>
                        <a class="btn btn-info" href="http://localhost:62747/SalaryReport/Details?Search=@Model.Search&Month=@Model.Month&Year=@Model.Year">Details</a>
                        <img class="print" src="https://img.icons8.com/ios-glyphs/30/000000/print.png" onclick="print()" />
                    </td>
                </tr>
                }
            </tbody>
        </table>
        </div>
    </div>
</div>

HrSystem/Views/SalaryReport/Details.cshtml
@using GraduationProject.Models;
@model List<Attendance_Leaving>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h1 class="p-4 my-2">
            <img class="mx-3" src="https://img.icons8.com/ios-filled/50/000000/men-age-group-5.png" />Personal Information
        </h1>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-sm-6 col-md-6 col-lg-6  ">
        <div class="p-2">
            <label class="h5">Employee Name :</label>
            <span class="fs-5">@ViewBag.Emp.Name</span>
        </div>

        <div class="p-2">
            <label class="h5">Department :</label>
            <span class="fs-5">@ViewBag.Emp.Dept.Name</span>
        </div>

        <div class="p-2">
            <label class="h5">Phone :</label>
            <span class="fs-5">@ViewBag.Emp.Phone</span>
        </div>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6  ">
        <div class="p-2">
            <label class="h5">Salary :</label>
            <span class="fs-5">@ViewBag.Emp.Salary</span>
        </div>
        <div class="p-2">
            <label class="h5">Attendance Time :</label>
            <span class="fs-5">@ViewBag.Emp.AttendanceTime</span>
        </div>
        <div class="p-2">
            <label class="h5">Leaving Time :</label>
            <span class="fs-5">@ViewBag.Emp.LeavingTime</span>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h1 class="p-4 my-2">
            <img class="mx-3" src="https://img.icons8.com/external-xnimrodx-lineal-color-xnimrodx/64/000000/external-setting-advertising-xnimrodx-lineal-color-xnimrodx-2.png" />General Settings
        </h1>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-sm-6 col-md-6 col-lg-6  ">
        <div class="p-2">
            <label class="h5">Extra :</label>
            <span class="fs-5">@ViewBag.General.Extra</span>
        </div>

        <div class="p-2">
            <label class="h5">Discount :</label>
            <span class="fs-5">@ViewBag.General.Discount</span>
        </div>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6  ">
        <div class="p-2">
            <label class="h5">DayOff 1 :</label>
            <span class="fs-5">@ViewBag.General.Dayoff_1</span>
        </div>

        <div class="p-2">
            <label class="h5">DayOff 2 :</label>
            <span class="fs-5">@ViewBag.General.Dayoff_2</span>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h1 class="p-4 my-2">
            <img class="mx-3" src="https://img.icons8.com/pastel-glyph/64/000000/sunbathe.png" />Official Holidays
        </h1>
        <hr />
    </div>
</div>
<div class="row">

    @foreach (var item in ViewBag.Holidays)
    {<div class="col-sm-6 col-md-6 col-lg-6">
            <div class="p-2">
                <label class="h5">Name :</label>
                <span class="fs-5">@item.Name</span>
            </div>
        </div>
                        <div class="col-sm-6 col-md-6 col-lg-6">
                            <div class="p-2">
                                <label class="h5">Date :</label>
                                <span class="fs-5">@item.Date</span>
                            </div>
                        </div>

                    }
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h1 class="p-4 my-2">
            <img class="mx-3" src="https://img.icons8.com/ios/50/000000/attendance-mark.png" />Attendance Information
        </h1>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
    </div>
    <table class="table w-100">
        <thead>
            <tr>
                <th>
                    Date
                </th>
                <th>
                    Attendance 
                </th>
                <th>
                    Leaving 
                </th>
                <th>
                    Deduction hours
                </th>
                <th>
                    Bonus Hours
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Date
                    </td>
                    <td>
                        @item.AttendanceTime
                    </td>

                    <td>
                        @item.LeavingTime

                    </td>
                    <td>
                        @if (TimeSpan.Parse(item.AttendanceTime).Hours > TimeSpan.Parse(ViewBag.Emp.AttendanceTime).Hours)
                        {
                            <span>@(TimeSpan.Parse(item.AttendanceTime).Hours - TimeSpan.Parse(ViewBag.Emp.AttendanceTime).Hours)</span>
                        }

                    </td>
                    <td>
                        @if (TimeSpan.Parse(item.LeavingTime).Hours > TimeSpan.Parse(ViewBag.Emp.LeavingTime).Hours)
                        {
                            <span>@(TimeSpan.Parse(item.LeavingTime).Hours - TimeSpan.Parse(ViewBag.Emp.LeavingTime).Hours)</span>
                        }

                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="form-group " style="margin-left:80%">
        <div>
            <a class="btn btn-info" href="http://localhost:62747/SalaryReport/CreateReport/?Search=@ViewBag.Rep.Search&Month=@ViewBag.Rep.Month&Year=@ViewBag.Rep.Year">Go To Report</a>

        </div>


    </div>
</div>

HrSystem/Views/SalaryReport/GetReport.cshtml
@model HrSystem.ViewModel.SalaryReport

<style>
    .table-wrapper{
        max-width:100%;
        overflow-x:scroll;
    }
</style>
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <h1 class="p-4 my-2">
                <img class="mx-3" src="https://img.icons8.com/ios-glyphs/30/000000/salary-female.png" />Salary Report
            </h1>
            <hr />
        </div>
    </div>


    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <form asp-controller="SalaryReport" asp-action="CreateReport" method="get">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="col-md-9 mx-3 form-group">
                    <input type="text" class="form-control" placeholder="Kindly enter employee name" asp-for="Search" />
                    <span asp-validation-for="Search" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @*<label class="col-md-3 label-control">Month</label>*@
                    <div class="col-md-9 mx-3">
                        <select class="form-control" id="month" asp-for="Month">
                            <option selected disabled>Month</option>
                            <option value="01">January</option>
                            <option value="02">February</option>
                            <option value="03">March</option>
                            <option value="04">April</option>
                            <option value="05">May</option>
                            <option value="06">June</option>
                            <option value="07">July</option>
                            <option value="08">August</option>
                            <option value="09">September</option>
                            <option value="10">October</option>
                            <option value="11">November</option>
                            <option value="12">December</option>
                        </select>
                    </div>
                    <span asp-validation-for="Month" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @*<label class="col-md-3 label-control">Year</label>*@
                    <div class="col-md-9 mx-3">
                        <select class="form-control" id="year" asp-for="Year">
                            <option selected disabled>Year</option>
                            <option value="1990">1990</option>
                            <option value="1991">1991</option>
                            <option value="1992">1992</option>
                            <option value="1993">1993</option>
                            <option value="1994">1994</option>
                            <option value="1995">1995</option>
                            <option value="1996">1996</option>
                            <option value="1997">1997</option>
                            <option value="1998">1998</option>
                            <option value="1999">1999</option>
                            <option value="2000">2000</option>
                            <option value="2001">2001</option>
                            <option value="2002">2002</option>
                            <option value="2003">2003</option>
                            <option value="2004">2004</option>
                            <option value="2005">2005</option>
                            <option value="2006">2006</option>
                            <option value="2007">2007</option>
                            <option value="2008">2008</option>
                            <option value="2009">2009</option>
                            <option value="2010">2010</option>
                            <option value="2011">2011</option>
                            <option value="2012">2012</option>
                            <option value="2013">2013</option>
                            <option value="2014">2014</option>
                            <option value="2015">2015</option>
                            <option value="2016">2016</option>
                            <option value="2017">2017</option>
                            <option value="2018">2018</option>
                            <option value="2019">2019</option>
                            <option value="2020">2020</option>
                            <option value="2021">2021</option>
                            <option value="2022">2022</option>
                            <option value="2023">2023</option>
                            <option value="2024">2024</option>
                            <option value="2025">2025</option>
                            <option value="2026">2026</option>
                            <option value="2027">2027</option>
                            <option value="2028">2028</option>
                        </select>
                    </div>
                    <span asp-validation-for="Year" class="text-danger"></span>
                </div>
                <div class="form-group d-flex justify-content-center">
                    <input type="submit" value="Search" class="btn btn-info" />
                </div>
            </form>
        </div>
    </div>
    <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <div class="table-wrapper">
        <table class="text-center table table-striped table-bordered zero-configuration">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Department
                    </th>
                    <th>
                        Salary
                    </th>
                    <th>
                        Attendance
                    </th>
                    <th>
                        Absence
                    </th>
                    <th>
                        Overtime hours
                    </th>
                    <th>
                        Deducted hours
                    </th>
                    <th>
                        Bonus
                    </th>
                    <th>
                        Deduction
                    </th>
                    <th>
                        Total
                    </th>
                    <th></th>
                </tr>
            </thead>
            </table>
            </div>
            </div>
            </div>


    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }