HrSystem/Models/OfficialHolidays.cs
using HrSystem.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GraduationProject.Models
{
    public class OfficialHolidays
    {
        public int ID { get; set; }
        [UniqueHolidays]
        public string Name { get; set; }
        [DataType(DataType.Date)]
        [UniqueDate]
        public System.DateTime Date { get; set; }

    }
}

HrSystem/Controllers/OfficialHolidaysController.cs
using GraduationProject.Models;
using GraduationProject.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GraduationProject.Controllers
{
    [Authorize]

    public class OfficialHolidaysController : Controller
    {
        private readonly IRepository<OfficialHolidays> repholi;
        private readonly HRSystem hRSystem;

        public OfficialHolidaysController(IRepository<OfficialHolidays> RepHoli, HRSystem hRSystem)
        {
            repholi = RepHoli;
            this.hRSystem = hRSystem;
        }
        public IActionResult Index()
        {
            var Holidays=repholi.GetAll();
            return View(Holidays);
        }

        public IActionResult Delete(int id)
        {

            repholi.Delete(id);
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {

            var Dept = repholi.GetById(id);

            return View(Dept);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveEdit(int id, OfficialHolidays newDept)
        {

            if (ModelState.IsValid == true)
            {
                repholi.Update(id, newDept);
                return RedirectToAction("Index");
            }

            return View("Edit", newDept);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(OfficialHolidays Newobj)
        {

            if (ModelState.IsValid == true)
            {
                repholi.Insert(Newobj);
                return RedirectToAction("Index");
            }
            return View("New", Newobj);
        }

        public IActionResult New()
        {

            return View();
        }
    }
}

HrSystem/Views/OfficialHolidays/Edit.cshtml
@model GraduationProject.Models.OfficialHolidays

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h1 class="p-4 my-2">
            <img class="mx-3" src="https://img.icons8.com/pastel-glyph/64/000000/sunbathe.png"/>Edit Official Holidays</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-lg-12">
        <form asp-controller="OfficialHolidays" asp-action="SaveEdit" asp-route-id="@Model.ID">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="col-md-3 control-label"></label>
                <div class="col-md-9 mx-3">
                <input asp-for="Name" class="form-control" />
                </div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="col-md-3 control-label"></label>
                <div class="col-md-9 mx-3">
                <input asp-for="Date" class="form-control" />
                </div>
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="d-flex justify-content-center">
                <span class="form-group mx-2">
                <input type="submit" value="Save" class="btn btn-primary" />
            </span>
            <span class="form-group">
                <a asp-controller="OfficialHolidays" asp-action="Index" class="btn btn-danger">Cancel</a>
            </span>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HrSystem/Views/OfficialHolidays/Index.cshtml
@model IEnumerable<GraduationProject.Models.OfficialHolidays>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h1 class="p-4 my-2">
            <img class="mx-3" src="https://img.icons8.com/pastel-glyph/64/000000/sunbathe.png"/>Official Holidays</h1>
    </div>
</div>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 " >
        <a class="btn btn-danger" style="float:right;clear:both;" asp-controller="OfficialHolidays" asp-action="New">Add New Official Holidays</a>
        <div style="clear:both;"></div>
        <hr />
    </div>
</div>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <table class="table table-striped table-bordered zero-configuration">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                <a class="btn btn-info" asp-controller="OfficialHolidays" asp-action="Edit" asp-route-id="@item.ID" onclick="Edit()">Edit</a>
                <a class="btn btn-danger" asp-controller="OfficialHolidays" asp-action="Delete" asp-route-id="@item.ID" onclick="Delete()">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>
</div>
<script>
    function Edit(){
        var respond=confirm("Do You Want To Edit?!");
        if(!respond){
            event.preventDefault();
        }
    }

    function Delete(){
        var respond=confirm("Do You Want To Delete?!");
        if(!respond){
            event.preventDefault();
        }
    }
</script>

HrSystem/Views/OfficialHolidays/New.cshtml
@model GraduationProject.Models.OfficialHolidays

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h1 class="p-4 my-2">
           <img class="mx-3" src="https://img.icons8.com/pastel-glyph/64/000000/sunbathe.png"/> Official Holidays</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-lg-12">
        <form asp-controller="OfficialHolidays" asp-action="Insert">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="col-md-3 control-label"></label>
                <div class="col-md-9 mx-3">
                <input asp-for="Name" class="form-control" />
                </div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="col-md-3 control-label"></label>
                <div class="col-md-9 mx-3">
                <input asp-for="Date" class="form-control" />
                </div>
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="d-flex justify-content-center">
                <span class="form-group mx-2">
                <input type="submit" value="ADD" class="btn btn-primary" />
            </span>
            <span class="form-group">
                <a asp-controller="OfficialHolidays" asp-action="Index" class="btn btn-danger">Cancel</a>
            </span>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}